services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_cs
      - POSTGRES_USER=django_cs
      - POSTGRES_PASSWORD=mysecretpassword
  web:
    build:
      context: ..
      dockerfile: cs_app/Dockerfile
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_CS_PASSWORD=mysecretpassword
    depends_on:
      - db
